// this file was generated by gomacro command: import _i "github.com/muazhari/gomacro-custom/base/paths"
// DO NOT EDIT! Any change will be lost when the file is re-generated

package paths

import (
	r "reflect"

	"github.com/muazhari/gomacro-custom/imports"
)

// reflection: allow interpreted code to import "github.com/muazhari/gomacro-custom/base/paths"
func init() {
	imports.Packages["github.com/muazhari/gomacro-custom/base/paths"] = imports.Package{
		Binds: map[string]r.Value{
			"DirName":                  r.ValueOf(DirName),
			"FileName":                 r.ValueOf(FileName),
			"GetImportsSrcDir":         r.ValueOf(GetImportsSrcDir),
			"GoSrcDir":                 r.ValueOf(&GoSrcDir).Elem(),
			"RemoveFinalSlash":         r.ValueOf(RemoveFinalSlash),
			"Subdir":                   r.ValueOf(Subdir),
			"SymbolFromImportsPackage": r.ValueOf(&SymbolFromImportsPackage).Elem(),
			"UserHomeDir":              r.ValueOf(UserHomeDir),
		},
	}
}
